# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malt',
            name='name',
        ),
        migrations.AddField(
            model_name='hop',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='inventory.Hop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malt',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='inventory.Malt'),
            preserve_default=False,
        ),
    ]
