# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20160528_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hop',
            name='name',
        ),
    ]
