# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 20, 14, 26, 9, 821983, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brewlog.Entry'),
        ),
    ]
