# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0002_auto_20160520_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewlog.Entry'),
        ),
    ]
