# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0005_auto_20160520_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='brewlog.Entry'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='brewlog.Entry'),
        ),
        migrations.AlterField(
            model_name='log',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='brewlog.Entry'),
        ),
    ]
