# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0006_auto_20160521_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='fermentationTemperature',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fermentationTime',
        ),
        migrations.AddField(
            model_name='entry',
            name='fermentation_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='fermentation_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='batch_size',
            field=models.IntegerField(default=19, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='boil_time',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 21, 12, 43, 5, 169066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='equipment_loss',
            field=models.DecimalField(decimal_places=1, default=0.4, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evaporation_factor',
            field=models.DecimalField(decimal_places=2, default=0.95, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fg',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grain_absorption',
            field=models.DecimalField(decimal_places=2, default=1.08, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grain_bill',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grain_temperature',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mash_temperature',
            field=models.IntegerField(default=67, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mash_thickness',
            field=models.DecimalField(decimal_places=2, default=2.61, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mash_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='og',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='percent_boiloff',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sparge_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='trub_loss',
            field=models.DecimalField(decimal_places=1, default=1.9, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wort_shrinkage',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='yeast',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
