# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0007_auto_20160521_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 21, 14, 49, 33, 869686, tzinfo=utc)),
        ),
    ]
