# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0007_auto_20160521_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 12, 30, 55, 51497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
