# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0009_auto_20160522_1236'),
        ('brewlog', '0008_auto_20160521_1449'),
    ]

    operations = [
    ]
