# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 22, 35, 22, 633045, tzinfo=utc)),
        ),
    ]
