# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0012_auto_20160524_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 8, 53, 16, 558290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 8, 53, 16, 556727, tzinfo=utc)),
        ),
    ]
