# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0013_auto_20160524_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 8, 55, 51, 643951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='brew',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brews', to='brewlog.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 8, 55, 51, 642357, tzinfo=utc)),
        ),
    ]
