# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0014_auto_20160524_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 30, 52, 238218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 30, 52, 236635, tzinfo=utc)),
        ),
    ]
