# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0015_auto_20160525_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trub_loss', models.DecimalField(decimal_places=1, default=1.9, max_digits=3, null=True)),
                ('equipment_loss', models.DecimalField(decimal_places=1, default=0.4, max_digits=3, null=True)),
                ('mash_thickness', models.DecimalField(decimal_places=2, default=2.61, max_digits=3, null=True)),
                ('wort_shrinkage', models.IntegerField(default=4, null=True)),
                ('grain_absorption', models.DecimalField(decimal_places=2, default=1.08, max_digits=3, null=True)),
                ('percent_boiloff', models.IntegerField(default=7, null=True)),
                ('evaporation_factor', models.DecimalField(decimal_places=2, default=0.95, max_digits=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='equipment_loss',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='evaporation_factor',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='grain_absorption',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='grain_bill',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mash_thickness',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='percent_boiloff',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='trub_loss',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='wort_shrinkage',
        ),
        migrations.AlterField(
            model_name='brew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 7, 22, 45, 802097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 7, 22, 45, 800257, tzinfo=utc)),
        ),
    ]
