# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brewlog', '0017_auto_20160526_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 10, 31, 22, 519501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 10, 31, 22, 515851, tzinfo=utc)),
        ),
    ]
